import Head from 'next/head';

// Styles
import styles from '../styles/Home.module.css';

// Hooks
import { useAuth } from '../services/auth';

const Home = () => {
    const auth = useAuth();

    return (
        <div className={styles.container}>
            <Head>
                <title>Saas Template</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {auth?.user ? (
                    <button onClick={() => auth.signOut()}>Sign out</button>
                ) : (
                    <button onClick={() => auth.signinWithGithub()}>
                        Sign in
                    </button>
                )}
                <div>{auth?.user?.email}</div>
            </main>
        </div>
    );
};

export default Home;
